@startuml sequence_diagram_tambah_nilai
hide footbox
autonumber

actor Administrator
boundary nilai.index
control JurusanController
control TahunAjaranController
control KelasController
control MahasiswaController
control NilaiController
entity Jurusan
entity TahunAjaran
entity Kelas
entity Mahasiswa
entity Nilai


nilai.index -> Administrator : Menampilkan halaman Nilai

activate nilai.index


Administrator -> nilai.index : Memilih jurusan pada dropdown


nilai.index -> TahunAjaranController : all()
activate TahunAjaranController

TahunAjaranController -> TahunAjaran : with()->get()
activate TahunAjaran
TahunAjaran -> TahunAjaranController : data

deactivate TahunAjaran
TahunAjaranController -> nilai.index : response(data)
deactivate TahunAjaranController
nilai.index -> Administrator : Merender data tahun ajaran pada dropdown

Administrator -> nilai.index : Memilih tahun ajaran pada dropdown

nilai.index -> KelasController : all()
activate KelasController

KelasController -> Kelas : with()->get()
activate Kelas
Kelas -> KelasController : data

deactivate Kelas
KelasController -> nilai.index : response(data)
deactivate KelasController

nilai.index -> Administrator : Merender data Kelas pada tabel

alt Menambah Nilai

Administrator -> nilai.index : Memilih Kelas pada tabel

nilai.index -> Administrator : Menampilkan pop-up modal tambah nilai mahasiswa

nilai.index -> KelasController : allRincianKelas()

activate KelasController

KelasController -> Mahasiswa : with()->get()
activate Mahasiswa
Mahasiswa -> KelasController : data

deactivate Mahasiswa
KelasController -> nilai.index : response(data)
deactivate KelasController

nilai.index -> Administrator : Merender data Mahasiswa pada tabel

Administrator -> nilai.index : Mengisi nilai pada input field masing-masing mahasiswa

Administrator -> nilai.index : Menekan tombol simpan

nilai.index -> NilaiController : store()

activate NilaiController

NilaiController -> Nilai : create()

activate Nilai

deactivate Nilai

NilaiController -> nilai.index : response(message)

deactivate NilaiController

nilai.index -> Administrator : Menampilkan toast berisikan pesan

else Batal mengubah Nilai

Administrator -> nilai.index : Menekan tombol batal / silang

end

nilai.index -> Administrator : Menutup pop-up modal tambah Nilai

@enduml