@startuml sequence_diagram_lihat_pengajaran
hide footbox
autonumber

actor Administrator
boundary beranda.index
boundary mengajar.index
control MengajarController
control Controller
entity Mengajar

beranda.index -> Administrator : Menampilkan halaman Beranda

activate beranda.index

Administrator -> beranda.index : Menekan menu Mengajar

beranda.index -> MengajarController : index()

activate MengajarController

MengajarController -> Controller : renderPage()

deactivate MengajarController

activate Controller

Controller --> mengajar.index : view()

deactivate beranda.index

activate mengajar.index

deactivate Controller

mengajar.index -> Administrator : Menampilkan halaman Mengajar

mengajar.index -> MengajarController  : all()

activate MengajarController

MengajarController -> Mengajar : with()->get()

activate Mengajar

Mengajar -> MengajarController : data

deactivate Mengajar

MengajarController -> mengajar.index : response(data)

deactivate MengajarController

mengajar.index -> Administrator : Merender data pada tabel Mengajar

@enduml