@startuml sequence_diagram_tambah_nilai
hide footbox
autonumber

actor Administrator
boundary mengajar.index
control MengajarController
control KelasController
control DosenController
entity Mengajar
entity Kelas
entity Dosen

mengajar.index -> Administrator : Menampilkan halaman Akta Mengajar

Administrator -> mengajar.index : Menekan tombol tambah Mengajar

alt Mengubah Mengajar

mengajar.index -> Administrator : Menampilkan pop-up modal tambah Mengajar


mengajar.index -> KelasController  : all()

activate KelasController

KelasController -> Kelas : with()->get()

activate Kelas

Kelas -> KelasController : data

deactivate Kelas

KelasController -> mengajar.index : response(data)

deactivate KelasController

mengajar.index -> Administrator : Merender data kelas pada dropdown pilih kelas



mengajar.index -> DosenController  : all()

activate DosenController

DosenController -> Dosen : with()->get()

activate Dosen

Dosen -> DosenController : data

deactivate Dosen

DosenController -> mengajar.index : response(data)

deactivate DosenController

mengajar.index -> Administrator : Merender data Dosen pada dropdown pilih Dosen

Administrator -> mengajar.index : Memilih Jurusan
Administrator -> mengajar.index : Memilih Dosen


Administrator -> mengajar.index : Menekan tombol simpan

mengajar.index -> MengajarController : store()

activate MengajarController

MengajarController -> Mengajar : create()

activate Mengajar

deactivate Mengajar

MengajarController -> mengajar.index : response(message)

deactivate MengajarController

mengajar.index -> Administrator : Menampilkan toast berisikan pesan

else Batal mengubah Mengajar

Administrator -> mengajar.index : Menekan tombol batal / silang

end

mengajar.index -> Administrator : Menutup pop-up modal tambah Mengajar

@enduml