@startuml usecase_akademik
left to right direction
skinparam packageStyle rectangle
actor Mahasiswa
actor Admin
rectangle "Sistem Akademik STAI Auliaurrasyidin (Modul KHS, Modul Kelas dan Modul Pengajaran) " {

    Mahasiswa --- (Melihat Nilai)

    Mahasiswa --- (Melihat Kelas)

    Mahasiswa --- (Melihat Daftar Mengajar)

    Admin --- (Manajemen Profil)
    Mahasiswa --- (Manajemen Profil)
    note top of (Manajemen Profil) : Lihat, Ubah

    Admin --- (Manajemen Kelas)
    note top of (Manajemen Kelas) : Lihat, Ubah, Tambah, Hapus

    Admin --- (Manajemen Pengajaran)
    note top of (Manajemen Pengajaran) : Lihat, Ubah, Tambah, Hapus

    Admin --- (Manajemen Nilai)
    note top of (Manajemen Nilai) : Lihat, Ubah, Tambah, Hapus

    (Melihat Nilai) ..> (Login) : include
    (Melihat Kelas) ..> (Login) : include
    (Melihat Daftar Mengajar) ..> (Login) : include
    (Manajemen Profil) ..> (Login) : include
    (Manajemen Kelas) ..> (Login) : include
    (Manajemen Nilai) ..> (Login) : include
    (Manajemen Pengajaran) ..> (Login) : include

    }
@enduml