@startuml usecase_akademik
left to right direction
skinparam packageStyle rectangle
actor mahasiswa
actor admin
rectangle akademik {
    mahasiswa -- (Melihat IPK)
    mahasiswa -- (Melihat kelas)
    mahasiswa -- (Melihat jadwal)
    mahasiswa -- (manajemen profil)
    (manajemen profil) -- admin
    (manajemen kelas) -- admin
    (manajemen pengajaran) -- admin
}
@enduml