@startuml usecase_akademik
left to right direction
skinparam packageStyle rectangle
actor Mahasiswa
actor Admin
rectangle "Sistem Akademik STAI Auliaurrasyidin (Modul Nilai, Modul Kelas dan Modul Akta Ajar) " {

    Mahasiswa --- (Melihat Nilai)

    Mahasiswa --- (Melihat Kelas)

    Mahasiswa --- (Melihat Akta Ajar)

    Admin --- (Manajemen Profil)
    Mahasiswa --- (Manajemen Profil)
    note top of (Manajemen Profil) : Lihat, Ubah

    Admin --- (Manajemen Kelas)
    note top of (Manajemen Kelas) : Lihat, Ubah, Tambah, Hapus

    Admin --- (Manajemen Akta Ajar)
    note top of (Manajemen Akta Ajar) : Lihat, Ubah, Tambah, Hapus

    Admin --- (Manajemen Nilai)
    note top of (Manajemen Nilai) : Lihat, Ubah, Tambah, Hapus

    (Melihat Nilai) ..> (Login) : include
    (Melihat Kelas) ..> (Login) : include
    (Melihat Akta Ajar) ..> (Login) : include
    (Manajemen Profil) ..> (Login) : include
    (Manajemen Kelas) ..> (Login) : include
    (Manajemen Nilai) ..> (Login) : include
    (Manajemen Akta Ajar) ..> (Login) : include

    }
@enduml